<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class OrganizationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currentTime = Carbon::now();
        $data = [
            [
                'organization_type_id' => 1,
                'organization_name' => 'PUP',
                'organization_acronym' => 'PUP',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'pup',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'PASOA',
                'organization_acronym' => 'PASOA',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'pasoa',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'Computer Society',
                'organization_acronym' => 'CS',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'ComputerSociety',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'aeces',
                'organization_acronym' => 'aeces',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'aeces',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'jpsme',
                'organization_acronym' => 'jpsme',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'jpsme',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'jpia',
                'organization_acronym' => 'jpia',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'jpia',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'mentors',
                'organization_acronym' => 'mentors',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'mentors',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'jma',
                'organization_acronym' => 'jma',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'jma',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 1,
                'organization_name' => 'jpmap',
                'organization_acronym' => 'jpmap',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'jpmap',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'csc',
                'organization_acronym' => 'csc',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'csc',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'pupukaw',
                'organization_acronym' => 'pupukaw',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'pupukaw',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'erg',
                'organization_acronym' => 'erg',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'erg',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'test',
                'organization_acronym' => 'test',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'test',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'test2',
                'organization_acronym' => 'test2',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'test2',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],
            [
                'organization_type_id' => 2,
                'organization_name' => 'qwqwqw',
                'organization_acronym' => 'qwqwqw',
                'organization_details' => '...',
                'organization_primary_color' => '#1bbede',
                'organization_secondary_color' => '#1bbede',
                'organization_tertiary_color' => '#1bbede',
                'organization_slug' => 'qwqwqw',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => 1,
            ],

        ];
        DB::table('organizations')->insert($data);
    }
}
