<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $status = 1;
        $course = 1;
        $gender = 1;
        $currentTime = Carbon::now();
        $data = [
            [
                //1
                'course_id' => NULL,
                'gender_id' => NULL, 
                'email' => 'super-admin@email.com', 
                'password' => Hash::make('super-admin@email.com'),
                'student_number' => NULL, 
                'first_name' => 'Super Admin',
                'middle_name' => 'I',
                'last_name' => 'Am',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456124',
                'address' => 'Bulacan Malolos',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,
            ],
            [
                //2
                'course_id' => 1,
                'gender_id' => 1,
                'email' => 'bsa-homepage@email.com', 
                'password' => Hash::make('bsa-homepage@email.com'),
                'student_number' => '2018-12346-TG-0', 
                'first_name' => 'John',
                'middle_name' => 'Faraday',
                'last_name' => 'Doe',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456700',
                'address' => 'Bulacan Malolos',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,
            ],
            [
                // 3qar
                'course_id' => 11,
                'gender_id' => 2,
                'email' => 'lullabyangela@gmail.com', 
                'password' => Hash::make('lullabyangela@gmail.com'),
                'student_number' => '2019-00404-TG-0', 
                'first_name' => 'Victoria Angela Marie',
                'middle_name' => 'Aquino',
                'last_name' => 'Dolor',
                'date_of_birth' => '2000-11-04',
                'mobile_number' => '+639164546149',
                'address' => '144 A. Reyes St., New Lower Bicutan, Taguig City',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                //4 qar
                'course_id' => $course,
                'gender_id' => $gender, 
                'email' => 'jaceamaguin@gmail.com', 
                'password' => Hash::make('jaceamaguin@gmail.com'),
                'student_number' => '2018-00167-TG-0', 
                'first_name' => 'Juan Carlos',
                'middle_name' => NULL,
                'last_name' => 'Amaguin',
                'date_of_birth' => '1998-11-08',
                'mobile_number' => '+639175391998',
                'address' => '20 Kirishima St. BF Thai Las Piñas City',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                //5
                'course_id' => 1,
                'gender_id' => 1,
                'email' => 'bsa-membership@email.com', 
                'password' => Hash::make('bsa-membership@email.com'),
                'student_number' => '2018-12345-TG-0', 
                'first_name' => 'John',
                'middle_name' => 'Faraday',
                'last_name' => 'Doe',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456700',
                'address' => 'Bulacan Malolos',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,
            ],
            [
                //6
                'course_id' => 1,
                'gender_id' => 1,
                'email' => 'bsa-gpoa@email.com', 
                'password' => Hash::make('bsa-gpoa@email.com'),
                'student_number' => '2018-12348-TG-0', 
                'first_name' => 'John',
                'middle_name' => 'Faraday',
                'last_name' => 'Doe',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456700',
                'address' => 'Bulacan Malolos',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,
            ],
            [
                //7
                'course_id' => 1,
                'gender_id' => 1,
                'email' => 'bsa-finance@email.com', 
                'password' => Hash::make('bsa-finance@email.com'),
                'student_number' => '2018-12347-TG-0', 
                'first_name' => 'John',
                'middle_name' => 'Faraday',
                'last_name' => 'Doe',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456700',
                'address' => 'Bulacan Malolos',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,
            ],
            [
                //8 normal user
                'course_id' => 1,
                'gender_id' => 2, 
                'email' => 'bsa-member@email.com', 
                'password' => Hash::make('bsa-member@email.com'),
                'student_number' => '2018-00012-TG-0', 
                'first_name' => 'BSA John',
                'middle_name' => 'Fitzgerald',
                'last_name' => 'Kennedy',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '+639123456710',
                'address' => 'Lower Bicutan Taguig City',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => $status,       
            ],
            [
                // 9 qar AVP Docu
                'course_id' => 11,
                'gender_id' => 1,
                'email' => 'bryantpaulbabac07302001@gmail.com', 
                'password' => Hash::make('bryantpaulbabac07302001@gmail.com'),
                'student_number' => '2020-00197-TG-0', 
                'first_name' => 'Bryant Paul',
                'middle_name' => 'Sana',
                'last_name' => 'Babac',
                'date_of_birth' => '2001-07-30',
                'mobile_number' => '+639667344635',
                'address' => 'Imus City, Cavite',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                // 10 Adviser
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'adviser@email.com', 
                'password' => Hash::make('adviser@email.com'),
                'student_number' => NULL, 
                'first_name' => 'Adviser',
                'middle_name' => 'I',
                'last_name' => 'Am',
                'date_of_birth' => '2001-01-01',
                'mobile_number' => '+639667344637',
                'address' => 'Taguig',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            // HOMEPAGE USERS
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'cs@email.com', 
                'password' => Hash::make('cs@email.com'),
                'student_number' => NULL, 
                'first_name' => 'CS',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'aeces@email.com', 
                'password' => Hash::make('aeces@email.com'),
                'student_number' => NULL, 
                'first_name' => 'aeces',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'jpsme@email.com', 
                'password' => Hash::make('jpsme@email.com'),
                'student_number' => NULL, 
                'first_name' => 'jpsme',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'jpia@email.com', 
                'password' => Hash::make('jpia@email.com'),
                'student_number' => NULL, 
                'first_name' => 'jpia',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'mentors@email.com', 
                'password' => Hash::make('mentors@email.com'),
                'student_number' => NULL, 
                'first_name' => 'mentors',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'jma@email.com', 
                'password' => Hash::make('jma@email.com'),
                'student_number' => NULL, 
                'first_name' => 'jma',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'jpmap@email.com', 
                'password' => Hash::make('jpmap@email.com'),
                'student_number' => NULL, 
                'first_name' => 'jpmap',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'csc@email.com', 
                'password' => Hash::make('csc@email.com'),
                'student_number' => NULL, 
                'first_name' => 'csc',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'pupukaw@email.com', 
                'password' => Hash::make('pupukaw@email.com'),
                'student_number' => NULL, 
                'first_name' => 'pupukaw',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
            [
                'course_id' => NULL,
                'gender_id' => NULL,
                'email' => 'erg@email.com', 
                'password' => Hash::make('erg@email.com'),
                'student_number' => NULL, 
                'first_name' => 'erg',
                'middle_name' => '...',
                'last_name' => '...',
                'date_of_birth' => '2000-01-01',
                'mobile_number' => '...',
                'address' => '...',
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
                'status' => $status,
            ],
        ];

        DB::table('users')->insert($data);
    }
}